@echo off
echo Iniciando el backend...
start cmd /k "cd C:\Users\usuario1\Desktop\SAS 2\SASBACK && node server.js"
echo Esperando 5 segundos para que el backend se inicie...
timeout /t 5 /nobreak
echo Iniciando el frontend...
start cmd /k "cd C:\Users\usuario1\Desktop\SAS 2\SASFRONT && npx vite"
echo Esperando 5 segundos para que el frontend se inicie...
timeout /t 5 /nobreak
echo Abriendo la aplicación en el navegador...
start http://localhost:5173
echo Hecho!
